# This is a basic workflow to help you get started with Actions

name: My Resume CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # COPIED FROM Github Action for LaTeX
      - name: Github Action for LaTeX
        # You may pin to the exact commit or the version.
        # uses: xu-cheng/latex-action@fea2c87db829f594ce87348291f235074ffd8eeb
        uses: xu-cheng/latex-action@v2
        with:
          # The root LaTeX file to be compiled
          root_file: my_resume.tex
          # Arbitrary bash codes to be executed before compiling LaTeX documents
          # TODO not sure if I want to spend the time to update everything... might be better to only do my packages I need
          pre_compile: "tlmgr update --self && tlmgr update --all"
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: my_resume.pdf
